services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: consilio_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: asdfghjkl

  backend:
    build:
      context: .
      dockerfile: Dockerfile.django
    volumes:
      - ./consilio_django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=consilio_db
      - DB_USER=admin
      - DB_PASSWORD=asdfghjkl
      - DB_HOST=db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.vue
    volumes:
      - ./consilio_vue:/app
    ports:
      - "8080:8080"
    depends_on:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: asdfghjkl
    depends_on:
      - db

volumes:
  postgres_data:

