# Generated by Django 5.2.1 on 2025-05-17 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redmine', '0002_alter_issue_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Role',
        ),
        migrations.AddField(
            model_name='user',
            name='redmine_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
