# Generated by Django 5.2.1 on 2025-06-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redmine', '0003_remove_user_role_user_redmine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent_id',
            field=models.IntegerField(blank=True, db_column='Parent_ID', help_text='ID nadřazeného projektu', null=True),
        ),
    ]
