# Generated by Django 5.2.1 on 2025-06-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redmine', '0004_project_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dark_mode',
            field=models.BooleanField(default=True, help_text='True = tmavý režim, False = světlý režim'),
        ),
    ]
