# Generated by Django 5.2.3 on 2025-06-23 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Redmine', '0005_user_dark_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='dark_mode',
        ),
    ]
