# Generated by Django 5.2.3 on 2025-08-17 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redmine', '0008_alter_issue_assigned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assigned',
            field=models.PositiveIntegerField(blank=True, db_column='assigned_id', help_text='Redmine ID uživatele přiřazeného k úloze', null=True),
        ),
    ]
