# Generated by Django 5.2.3 on 2025-08-19 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Redmine', '0011_alter_issue_assigned_alter_issue_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='Redmine.project'),
        ),
    ]
